In [7]:
'''
Subset Sum Problem
Given a set of non-negative integers, and a value sum, determine if there is a subset of the given set with sum equal 
to given sum.
Example:
Input:  set[] = {3, 34, 4, 12, 5, 2}, sum = 9
Output:  True  //There is a subset (4, 5) with sum 9.
'''

arr = np.array([3, 34, 4, 12, 5, 7, 6, 9, 2])
s = 25

def findSubsetSum(arr, n, s):
    if(0 == s):
        return True
    if((0 == n) & (0 !=s)):
        return False
    if(arr[n-1] > s):
        return findSubsetSum(arr, n-1, s)
    return (findSubsetSum(arr, n-1, s-arr[n-1]) | findSubsetSum(arr, n-1, s))

print (findSubsetSum(arr, arr.size, s))

True


In [8]:
'''
Print all subset of a given sum
'''
arr = np.array([3, 6, 9, 2, 5])

def printElement(arr, n, s, lable, list1):
    if((0 == n) & (0 == s)):
        print(list1)
        return
    
    if((0 == n) & (s == arr[0])):
        list1.append(arr[0])
        print(list1)
        return
    
    #Without current element
    if(lable[n-1][s]):
        list2 = list1.copy()
        printElement(arr, n-1, s, lable, list2)
    
    #consider current element
    if((s >= arr[n]) & lable[n-1][s-arr[n]]):
        list1.append(arr[n])
        printElement(arr, n-1, s-arr[n], lable, list1)
    
    
def printSum(arr, n, s):
    if((s < 0) | (0 == n)):
        return
    lable = np.zeros((n, s+1), dtype=np.int8)
    
    #lable the first element
    lable[0][arr[0]] = 1
    
    #sum 0 can be found with no element
    for i in range(n):
        lable[i][0] = 1
        
    #create a lable matrix
    for i in range(1,n):
        for j in range((s+1)):
            lable[i][j] = (lable[i-1][j] | lable[i-1][j-arr[i]]) if(arr[i] <= j) else lable[i-1][j]
    print (lable)
    
    if(0 == lable[n-1][s]):                                       
        print ('Not exisit!')
        return
    
    l = []
    printElement(arr, arr.size - 1, s, lable, l)
    
print (printSum(arr, arr.size, 11))

[[1 0 0 1 0 0 0 0 0 0 0 0]
 [1 0 0 1 0 0 1 0 0 1 0 0]
 [1 0 0 1 0 0 1 0 0 1 0 0]
 [1 0 1 1 0 1 1 0 1 1 0 1]
 [1 0 1 1 0 1 1 1 1 1 1 1]]
[2, 6, 3]
[2, 9]
[5, 6]
None
